$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: used-car-price-prediction-pipeline
experiment_name: used_car_price_prediction
description: Training Pipeline to predict price of used-cars using Decision Tree Regressor

inputs:
  input:
    type: uri_file
    path: azureml:used_car_data@latest
  test_train_ratio:
    type: number
    default: 0.2

outputs:
  train_data:
  test_data:
  model_info_output_path:

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    name: prep_data
    display_name: prep-data
    code: ../../../data-science/src
    command: >-
      python prep.py 
      --data ${{inputs.data}} 
      --test_train_ratio ${{inputs.test_train_ratio}}
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}}
    environment: azureml:machine_learning_E2E@latest
    inputs:
      data: ${{parent.inputs.input}}
      test_train_ratio: ${{parent.inputs.test_train_ratio}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    name: sweep_job
    display_name: sweep-job
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    sampling_algorithm: random
    trial: ./train.yml
    search_space:
      criterion:
        type: choice
        values: ["mse"]
      max_depth:
        type: choice
        values: [3, 5, 10, null]
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  register_model:
    name: register_model
    display_name: register-model
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model ${{inputs.model}}
    environment: azureml:machine_learning_E2E@latest
    inputs:
      model: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}